[project]
name = "comfy-sidebar"
description = "A compact and powerful layout overhaul for ComfyUI that makes generation results easier to browse, preview, compare, and manage."
version = "1.7.0"
license = { file = "LICENSE" }
dependencies = [
    "send2trash>=1.8.0",
]

[project.urls]
Repository = "https://github.com/m0rtus59/ComfyUI-ComfySidebar"

[tool.comfy]
PublisherId = "soundslikethunder"
DisplayName = "Comfy Sidebar"
Icon = "https://raw.githubusercontent.com/m0rtus59/ComfyUI-ComfySidebar/main/assets/icon.png"